---
name: Variables y procedimientos
locale: es
type: learning
beta: false
teacher_info: ''
language: javascript
id_format: "%05d"
order:
- 12
- 13
- 14
- 6
- 9
- 10
- 5
- 11
- 4
- 3
- 15
private: false
